### ISSUE TITLE
Error installing on Mac

### ISSUE THREAD

**Issue by blainesch** [sagold/zazu-dict#2]
Mac version: 10.12.2 (sierra)
Zazu version: 0.2.3
zazu-dict versio: 03c777e1da01970a6cdbc5d2399717185520d0a1

To reproduce on Mac, add `sagold/zazu-dict` to your list of plugins, and start up zazu. It won't finish installing and you'll see the following error in your developer tools:

~~~
Uncaught Error: node-expat@2.3.15 install: `node-gyp rebuild`
spawn ENOENT
~~~

I believe this is an issue with the native module installing `node-expat` which is part of `xml2json`.

**Comment by sagold** [comment]
@blainesch Thank you for the details. I replace the parser.

**Comment by sagold** [comment]
Hi blainisch.

I [replaced the parser](01e4ca0dc137953a53bff9ac81ce0a8d1552c19a) and published the plugin. Keep up the good work.

**Comment by blainesch** [comment]
Thank you! [:
